functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  
non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  # Нет конкретики в критериях удобства использования, нет критериев оценки оптимальности скорости работы
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  # Нет перечня интересующих заказчика платформ, если не брать во внимание этот пункт то относится к функциональным требованиям
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  # Нет четких критериев "большое количества трафика" 
implicit:
- Удобство верстки приложения при работе с мобильных устройств
- Корректность работы SPA
- Наличие ЛК пользователя с возможностью просмотра заказов и их отслеживания
